core/urls.py
from django.urls import path
from .views import CreateShorten, LinkPage, RedirectLink

app_name = 'core'
urlpatterns = [
    path('', CreateShorten.as_view(), name='home'),
    path('<int:pk>/', LinkPage.as_view(), name='detail'),
    path('<str:code>/', RedirectLink.as_view(), name='redirect'),
]

shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),

    path('a/admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.urls import reverse
from hashids import Hashids
import datetime

# Create your models here.
class LinkQuerySet(models.QuerySet):
    def decode_link(self, code):
        decode = Hashids(min_length=4, alphabet='abcdefghijklmnopqrstuvwxyz').decode(code)[0]
        self.filter(pk=decode).update(counter=models.F('counter') + 1)
        return self.filter(pk=decode).first().url

    def total_links(self):
        return self.count()

    def total_redirects(self):
        return self.aggregate(redirects=models.Sum('counter'))

    def dates(self, pk):
        return self.values('date').annotate(
            july=models.Sum('counter', filter=models.Q(date__gte=datetime.date(2019, 7, 1), date__lte=datetime.date(2019, 7, 30)))).filter(pk=pk)

class Link(models.Model):
    url = models.URLField()
    code = models.CharField(max_length=200, blank=True)
    date = models.DateField(auto_now_add=True)
    counter = models.PositiveIntegerField(default=0)

    links = LinkQuerySet.as_manager()

    class Meta:
        verbose_name_plural = 'Links'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.code:
            self.code = Hashids(min_length=4, alphabet='abcdefghijklmnopqrstuvwxyz').encode(self.pk)
            self.save()

    def get_absolute_url(self):
        return reverse('core:detail', kwargs={'pk': self.pk})

core/forms.py
from django import forms
from .models import Link

class ShortenerForm(forms.ModelForm):

    class Meta:
        model = Link
        fields = ('url',)
        widgets = {
        'url': forms.URLInput(attrs={'class': 'input is-rounded is-medium', 'placeholder': 'URL'}),
        }

core/views.py
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.base import RedirectView
from .models import Link
from .forms import ShortenerForm

# Create your views here.
class CreateShorten(CreateView):
    model = Link
    form_class = ShortenerForm
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_links'] = Link.links.total_links()
        context['total_redirects'] = Link.links.total_redirects()['redirects']
        return context

class LinkPage(DetailView):
    model = Link
    template_name = 'link.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['july'] = Link.links.dates(pk=self.kwargs['pk'])[0]['july']
        return context

class RedirectLink(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        try:
            return Link.links.decode_link(self.kwargs['code'])
        except IndexError:
            print("Error decode without data")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
  <title>{% block title %}{% endblock title %}</title>
</head>

<body>
  {% include 'navbar.html' %}
  {% block content %}{% endblock content %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Shortener{% endblock title %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4">
        <h1 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
        <h2 class="subtitle">
          Fusce quis turpis hendrerit, <strong>ultrices</strong> nibh quis, malesuada mauris. Praesent aliquam ligula
          in faucibus
          tempus
        </h2>
        <br>
        <form method="POST">
          {% csrf_token %}
          <div class="field has-addons">
            <div class="control">
              {{ form.url }}
            </div>
            <div class="control">
              <input type="submit" class="button is-info is-rounded is-medium" value="Shorten">
            </div>
          </div>
        </form>
      </div>
      <div class="column is-6 is-offset-2">
        <canvas id="myChart"></canvas>
      </div>
    </div>
  </div>
</section>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ["Links", "Redirects"],
      datasets: [
        {
          backgroundColor: ["#8e5ea2", "#3e95cd"],
          data: ["{{ total_links }}", "{{ total_redirects }}"]
        }
      ]
    },
    options: {
      legend: { display: false },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
  });
</script>
{% endblock content %}

templates/link.html
{% extends 'base.html' %}
{% block title %}Shortener Link{% endblock title %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4 is-offset-4">
        <div class="tags has-addons">
          <a href="{% url 'core:redirect' code=object.code %}" class="tag is-large">{{ request.META.HTTP_HOST }}</a>
          <span class="tag is-info is-large">/{{ object.code }}/</span>
        </div>
      </div>
    </div>
    <div class="box">
      <canvas id="myChart"></canvas>
    </div>
  </div>
</section>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      datasets: [{
        label: 'Redirects',
        backgroundColor: 'rgb(32, 156, 238)',
        borderColor: 'rgb(32, 156, 238)',
        data: [0, 0, 0, 0, 0, 0, "{{ july }}", 0, 0, 0, 0, 0]
      }]
    },
    options: {}
  })
</script>
{% endblock content %}

templates/navbar.html
<div class="container">
  <nav class="navbar">
    <div class="navbar-menu">
      <div class="navbar-start">
        <a href="{% url 'core:home' %}" class="navbar-item" style="padding-left: 0px;">
          Shortener URL
        </a>
      </div>
      <div class="navbar-end">
        <a class="navbar-item">
          Lorem
        </a>
        <a class="navbar-item">
          Lorem
        </a>
        <a class="navbar-item">
          Lorem
        </a>
      </div>
    </div>
  </nav>
</div>